version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: wai-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Info@1234 # AQUI VOCE POE SUA SENHA
      MYSQL_DATABASE: wai
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./module/persistence/src/main/resources/schema-main.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - wai-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wai-api
    restart: unless-stopped
    ports:
      - "8082:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - wai-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/wai
      - MYSQL_USER=root # SE SEU ROOT FOR DIFERENTE VC DEFINE AQUI TAMBEM
      - MYSQL_PASSWORD=Info@1234 # AQUI VOCE POE A SUA SENHA

volumes:
  mysql_data:
    driver: local

networks:
  wai-network:
    driver: bridge