version: '3.8'

services:
  # Banco de dados MySQL para desenvolvimento
  mysql-dev:
    image: mysql:8.0
    container_name: cashpoint-mysql-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: wai
      MYSQL_USER: admin
      MYSQL_PASSWORD: Info@1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ./module/persistence/src/main/resources/schema-mysql.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./module/persistence/src/main/resources/data-initialization.sql:/docker-entrypoint-initdb.d/02-data.sql
    networks:
      - cashpoint-dev-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis para desenvolvimento
  redis-dev:
    image: redis:7-alpine
    container_name: cashpoint-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - cashpoint-dev-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Adminer para gerenciar MySQL
  adminer:
    image: adminer:latest
    container_name: cashpoint-adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql-dev
    networks:
      - cashpoint-dev-network
    depends_on:
      mysql-dev:
        condition: service_healthy

volumes:
  mysql_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  cashpoint-dev-network:
    driver: bridge 