logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG

security:
  key:
    private: ${SECURITY_KEY_PRIVATE:classpath:app.key}
    public: ${SECURITY_KEY_PUBLIC:classpath:app.pub}

spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/wai}
    username: admin
    password: Info@1234

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update} # Em produção, use validate ou none e controle migrações com Flyway/Liquibase
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

# Para produção, restrinja o CORS no SecurityConfiguration
# Exemplo:
# configuration.setAllowedOriginPatterns(List.of("https://seu-dominio.com"));

decorator:
  datasource:
    p6spy:
      enable-logging: true