create table business_unit
(
    id          bigint generated by default as identity,
    name        varchar(100) not null unique,
    description text,
    created_at  timestamp(6) not null,
    updated_at  timestamp(6),
    primary key (id)
);

create table users
(
    created_at      timestamp(6) not null,
    id              uuid         not null,
    name            varchar(100) not null,
    email           varchar(30)  not null unique,
    username        varchar(30)  not null unique,
    image_url       varchar(200),
    password        varchar(200) not null,
    bio             varchar(500),
    business_unit_id bigint      not null,
    role            varchar(10)  not null,
    primary key (id)
);

alter table if exists users
    add constraint fk_users_business_unit foreign key (business_unit_id) references business_unit;